# Carregamento da base de dados

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np

In [2]:
base_casas = pd.read_csv('house_prices.csv')
base_casas

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [3]:
base_casas.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [4]:
base_casas.describe()

id         price      bedrooms     bathrooms   sqft_living  \
count  2.161300e+04  2.161300e+04  21613.000000  21613.000000  21613.000000   
mean   4.580302e+09  5.400881e+05      3.370842      2.114757   2079.899736   
std    2.876566e+09  3.671272e+05      0.930062      0.770163    918.440897   
min    1.000102e+06  7.500000e+04      0.000000      0.000000    290.000000   
25%    2.123049e+09  3.219500e+05      3.000000      1.750000   1427.000000   
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  7.700000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront          view     condition  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  21613.000000   
mean   1.510697e+04      1.494309      0.007542      0.234303      3.409430   
std    4.142051e+04      0.539989      0.086517      0.766318      0.650743   
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000   
50%    7.618000e+03      1.500000      0.000000      0.000000      3.000000   
75%    1.068800e+04      2.000000      0.000000      0.000000      4.000000   
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000   

              grade    sqft_above  sqft_basement      yr_built  yr_renovated  \
count  21613.000000  21613.000000   21613.000000  21613.000000  21613.000000   
mean       7.656873   1788.390691     291.509045   1971.005136     84.402258   
std        1.175459    828.090978     442.575043     29.373411    401.679240   
min        1.000000    290.000000       0.000000   1900.000000      0.000000   
25%        7.000000   1190.000000       0.000000   1951.000000      0.000000   
50%        7.000000   1560.000000       0.000000   1975.000000      0.000000   
75%        8.000000   2210.000000     560.000000   1997.000000      0.000000   
max       13.000000   9410.000000    4820.000000   2015.000000   2015.000000   

            zipcode           lat          long  sqft_living15     sqft_lot15  
count  21613.000000  21613.000000  21613.000000   21613.000000   21613.000000  
mean   98077.939805     47.560053   -122.213896    1986.552492   12768.455652  
std       53.505026      0.138564      0.140828     685.391304   27304.179631  
min    98001.000000     47.155900   -122.519000     399.000000     651.000000  
25%    98033.000000     47.471000   -122.328000    1490.000000    5100.000000  
50%    98065.000000     47.571800   -122.230000    1840.000000    7620.000000  
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000  
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000

In [5]:
base_casas.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

# Visualização dos dados

In [6]:
base_casas.corr()

ValueError: could not convert string to float: '20141013T000000'

In [ ]:
figura = plt.figure(figsize=(20,20))
sns.heatmap(base_casas.corr(), annot=True);

ValueError: could not convert string to float: '20141013T000000'

<Figure size 2000x2000 with 0 Axes>

# Pré-processamento dos dados

In [7]:
base_casas.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [8]:
X = base_casas.iloc[:, 3:19].values
X

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [9]:
X.shape

(21613, 16)

In [10]:
X[0]

array([ 3.00000e+00,  1.00000e+00,  1.18000e+03,  5.65000e+03,
        1.00000e+00,  0.00000e+00,  0.00000e+00,  3.00000e+00,
        7.00000e+00,  1.18000e+03,  0.00000e+00,  1.95500e+03,
        0.00000e+00,  9.81780e+04,  4.75112e+01, -1.22257e+02])

In [11]:
y = base_casas.iloc[:, 2].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [12]:
y.shape

(21613,)

In [13]:
X = np.array(X).astype('float32')
y = np.array(y).astype('float32')

In [14]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3, random_state=0)

In [15]:
X_treinamento.shape, X_teste.shape

((15129, 16), (6484, 16))

In [16]:
y_treinamento.shape, y_teste.shape

((15129,), (6484,))

In [17]:
X_treinamento.min(), X_treinamento.max()

(-122.514, 1651359.0)

# Configurações SageMaker

In [18]:
import sagemaker
import boto3
from sagemaker import Session

sagemaker.config INFO - Not applying SDK defaults from location: C:\ProgramData\sagemaker\sagemaker\config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: C:\Users\pacie\AppData\Local\sagemaker\sagemaker\config.yaml


In [19]:
session = sagemaker.Session()
bucket = 'pb-aws-teste2-s3'
subpasta_modelo = 'modelos/house-prices/linear-learner'
subpasta_dataset = 'datasets/house-prices'

In [20]:
role = 'arn:aws:iam::992382374294:role/service-role/AmazonSageMaker-ExecutionRole-20240615T181656'
print(role)

arn:aws:iam::992382374294:role/service-role/AmazonSageMaker-ExecutionRole-20240615T181656


In [21]:
import io
import sagemaker.amazon.common as smac # sagemaker commom library

buffer = io.BytesIO()
smac.write_numpy_to_dense_tensor(buffer, X_treinamento, y_treinamento)
buffer.seek(0)

0

In [22]:
import os
key = 'houses-train-data'
boto3.resource('s3').Bucket(bucket).Object(os.path.join(subpasta_dataset, 'train', key).replace('\\', '/')).upload_fileobj(buffer)

In [23]:
os.path.join(subpasta_dataset, 'train', key)

'datasets/house-prices\\train\\houses-train-data'

In [24]:
s3_train_data = 's3://{}/{}/train/{}'.format(bucket, subpasta_dataset, key)
print('Localização da base de treinamento: {}'.format(s3_train_data))

Localização da base de treinamento: s3://pb-aws-teste2-s3/datasets/house-prices/train/houses-train-data


In [25]:
output_location = 's3://{}/{}/output'.format(bucket, subpasta_modelo)
print('Modelo final será salvo em: {}'.format(output_location))

Modelo final será salvo em: s3://pb-aws-teste2-s3/modelos/house-prices/linear-learner/output


# Criação e treinamento do Linear Learner

In [26]:
boto3.Session().region_name

'us-east-1'

In [27]:
# https://docs.aws.amazon.com/sagemaker/latest/dg/linear-learner.html
# https://docs.aws.amazon.com/sagemaker/latest/dg/ecr-sa-east-1.html
container = sagemaker.image_uris.retrieve(framework = 'linear-learner', region=boto3.Session().region_name)

In [28]:
# https://aws.amazon.com/ec2/instance-types/
# https://docs.aws.amazon.com/pt_br/AWSEC2/latest/UserGuide/instance-types.html
# https://docs.aws.amazon.com/sagemaker/latest/dg/notebooks-available-instance-types.html
# https://sagemaker.readthedocs.io/en/stable/api/training/estimators.html
# https://aws.amazon.com/pt/about-aws/whats-new/2019/08/amazon-sagemaker-launches-managed-spot-training-saving-machine-learning-training-costs/
linear = sagemaker.estimator.Estimator(image_uri = container,
                                       role = role,
                                       instance_count = 1,
                                       instance_type = 'ml.m4.xlarge',
                                       output_path = output_location,
                                       sagemaker_session = session,
                                       use_stop_instances = True)

In [29]:
# https://docs.aws.amazon.com/sagemaker/latest/dg/ll_hyperparameters.html
linear.set_hyperparameters(feature_dim = 16,
                           predictor_type = 'regressor',
                           num_models = 16)

In [30]:
linear.fit({'train': s3_train_data})

INFO:sagemaker:Creating training-job with name: linear-learner-2024-06-16-15-16-38-002


2024-06-16 15:16:40 Starting - Starting the training job...
2024-06-16 15:17:06 Starting - Preparing the instances for training......
2024-06-16 15:17:55 Downloading - Downloading input data...
2024-06-16 15:18:20 Downloading - Downloading the training image......
2024-06-16 15:19:41 Training - Training image download completed. Training in progress..Docker entrypoint called with argument(s): train
Running default environment configuration script
[06/16/2024 15:20:02 INFO 139954502117184] Reading default configuration from /opt/amazon/lib/python3.8/site-packages/algorithm/resources/default-input.json: {'mini_batch_size': '1000', 'epochs': '15', 'feature_dim': 'auto', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': 'auto', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss'

# Deploy, previsões e avaliação

In [33]:
# https://aws.amazon.com/pt/ec2/instance-types/inf1/
linear_regressor = linear.deploy(initial_instance_count = 1, instance_type = 'ml.m4.xlarge')

INFO:sagemaker:Creating model with name: linear-learner-2024-06-16-15-21-23-090
INFO:sagemaker:Creating endpoint-config with name linear-learner-2024-06-16-15-21-23-090
INFO:sagemaker:Creating endpoint with name linear-learner-2024-06-16-15-21-23-090


--------!

In [34]:
from sagemaker.serializers import CSVSerializer
from sagemaker.deserializers import JSONDeserializer

In [35]:
linear_regressor.serializer = CSVSerializer()
linear_regressor.deserializer = JSONDeserializer()

In [36]:
X_teste.shape

(6484, 16)

In [37]:
results = linear_regressor.predict(X_teste)

In [38]:
results

{'predictions': [{'score': 396383.5},
  {'score': 1486271.5},
  {'score': 541275.5},
  {'score': 569959.5},
  {'score': 995759.5},
  {'score': 388723.5},
  {'score': 413159.5},
  {'score': 364535.5},
  {'score': 560251.5},
  {'score': 1230271.5},
  {'score': 712063.5},
  {'score': 379255.5},
  {'score': 389247.5},
  {'score': 282979.5},
  {'score': 843111.5},
  {'score': 397799.5},
  {'score': 356475.5},
  {'score': 687799.5},
  {'score': 357963.5},
  {'score': 564383.5},
  {'score': 365183.5},
  {'score': 407147.5},
  {'score': 627127.5},
  {'score': 195087.5},
  {'score': 599179.5},
  {'score': 297759.5},
  {'score': 471051.5},
  {'score': 672651.5},
  {'score': 912679.5},
  {'score': 498279.5},
  {'score': 1411899.5},
  {'score': 459315.5},
  {'score': 469355.5},
  {'score': 909419.5},
  {'score': 859091.5},
  {'score': 403979.5},
  {'score': 299223.5},
  {'score': 272611.5},
  {'score': 503791.5},
  {'score': 162823.5},
  {'score': 413639.5},
  {'score': 385923.5},
  {'score': 4653

In [39]:
previsoes = np.array([r['score'] for r in results['predictions']])

In [40]:
previsoes

array([ 396383.5, 1486271.5,  541275.5, ...,  329699.5,  221863.5,
        148915.5])

In [41]:
previsoes.shape, X_teste.shape

((6484,), (6484, 16))

In [42]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_teste, previsoes)
mse = mean_squared_error(y_teste, previsoes)
print('MAE = ', mae, '\nMSE = ', mse)

MAE =  123631.90222085132 
MSE =  42970397575.36999


In [43]:
# Não executar se fizer o tuning dos parâmetros
linear_regressor.delete_endpoint()

INFO:sagemaker:Deleting endpoint configuration with name: linear-learner-2024-06-16-15-21-23-090
INFO:sagemaker:Deleting endpoint with name: linear-learner-2024-06-16-15-21-23-090
